<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>{{url('sitemap/index.xml')}}</loc>
    </sitemap>
    <sitemap>
        <loc>{{url('sitemap/categories.xml')}}</loc>
    </sitemap>
    <sitemap>
        <loc>{{url('sitemap/tags.xml')}}</loc>
    </sitemap>
    <sitemap>
        <loc>{{url('sitemap/origins.xml')}}</loc>
    </sitemap>
</sitemapindex>

<?xml version="1.0" encoding="UTF-8"?> 
<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"> 
<url>
  <loc>https://babynamewizards.com</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/american</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/australian</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/christian</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/english</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/french</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/indian</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/more</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/A</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/B</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/C</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/D</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/E</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/F</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/G</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/H</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/I</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/J</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/K</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/L</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/M</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/N</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/O</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/P</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/Q</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/R</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/S</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/T</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/U</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/V</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/W</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/X</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/Y</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/boy/Z</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/A</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/B</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/C</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/D</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/E</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/F</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/G</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/H</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/I</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/J</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/K</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/L</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/M</loc>
</url>
<url>
  <loc>https://babynamewizards.com/baby-names/arabic/girl/N</loc>
</url>
</urlset>